#!/usr/bin/env python3
"""Deterministic Logisim 5.0.0 fixtures. Never writes circuits/manual/."""
from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as E

ROOT = Path(__file__).resolve().parents[1]


def attr(node, **values):
    for name, value in values.items():
        E.SubElement(node, "a", name=name, val=str(value).lower() if isinstance(value, bool) else str(value))
    return node


def loc(x, y):
    return f"({x},{y})"


def component(c, lib, name, x, y, **attrs):
    return attr(E.SubElement(c, "comp", lib=str(lib), name=name, loc=loc(x, y)), **attrs)


def wire(c, *points):
    for start, end in zip(points, points[1:]):
        if start != end:
            assert start[0] == end[0] or start[1] == end[1]
            E.SubElement(c, "wire", {"from": loc(*start), "to": loc(*end)})


def tunnel(c, x, y, label, width=1, facing="west"):
    return component(c, 0, "Tunnel", x, y, label=label, width=width, facing=facing, labelfont="SansSerif plain 12")


def pin(c, x, y, label, width=1, output=False):
    return component(c, 0, "Pin", x, y, label=label, width=width, output=output,
                     facing="west" if output else "east", tristate=False, labelloc="east" if output else "west")


def source(c, x, y, label, width=1, initial=None):
    node = pin(c, x, y, label, width)
    if initial is not None:
        attr(node, initial=hex(initial))
    wire(c, (x, y), (x + 40, y))
    tunnel(c, x + 40, y, label, width)


def sink(c, x, y, label, width=1, signal=None):
    gap = 120 if width > 1 else 100
    tunnel(c, x - gap, y, signal or label, width, "east")
    wire(c, (x - gap, y), (x, y))
    pin(c, x, y, label, width, True)


def port(c, x, y, label, width=1, side="left"):
    dx = -30 if side == "left" else 30
    wire(c, (x, y), (x + dx, y))
    tunnel(c, x + dx, y, label, width, "east" if side == "left" else "west")


def constant(c, x, y, value=0, width=1):
    return component(c, 0, "Constant", x, y, value=hex(value), width=width)


def text(c, x, y, value):
    component(c, 8, "Text", x, y, text=value, font="SansSerif plain 14", halign="left")


def gate(c, name, x, y, inputs, output, width=1):
    component(c, 1, name + " Gate", x, y, size=30, inputs=2, width=width)
    axis = 40 if name in ("XOR", "XNOR", "NAND", "NOR") else 30
    for dy, signal in zip((-10, 10), inputs):
        port(c, x - axis, y + dy, signal, width)
    port(c, x, y, output, width, "right")


def invert(c, x, y, input_name, output_name):
    component(c, 1, "NOT Gate", x, y, size=20)
    port(c, x - 20, y, input_name)
    port(c, x, y, output_name, side="right")


def dff(c, x, y, data, clock, q, reset="ZERO", name="state"):
    component(c, 4, "D Flip-Flop", x, y, appearance="classic", trigger="rising", label=name)
    port(c, x - 40, y + 20, data)
    port(c, x - 40, y, clock)
    port(c, x, y, q, side="right")
    wire(c, (x - 10, y + 30), (x - 10, y + 60), (x + 20, y + 60))
    tunnel(c, x + 20, y + 60, reset)
    constant(c, x - 30, y + 30)


def circuit(project, name):
    c = E.SubElement(project, "circuit", name=name)
    attr(c, appearance="classic", circuit=name)
    return c


def project(main, bridge=False):
    p = E.Element("project", source="5.0.0", version="1.0")
    p.append(E.Comment("GENERATED by tools/generate_circuits.py; edit the generator, not this file."))
    for lib, desc in [(0,"Wiring"),(1,"Gates"),(4,"Memory"),(5,"I/O"),(8,"Base")]:
        E.SubElement(p,"lib",name=str(lib),desc="#"+desc)
    if bridge:
        E.SubElement(p, "lib", name="10", desc="jar#../../build/bitwright-bridge.jar#org.bitwright.bridge.BitwrightLibrary")
    if bridge:
        E.SubElement(p, "lib", name="11", desc="file#../../circuits/manual/foundations.circ")
    E.SubElement(p, "main", name=main)
    attr(E.SubElement(p, "options"), showgrid=True, simlimit=10000, simrand=0)
    mappings = E.SubElement(p,"mappings")
    E.SubElement(mappings,"tool",lib="8",name="Menu Tool",map="Button3")
    toolbar = E.SubElement(p,"toolbar")
    for name in ("Poke Tool", "Edit Tool", "Wiring Tool", "Text Tool"):
        E.SubElement(toolbar,"tool",lib="8",name=name)
    return p


def foundations():
    p = project("LoadBit")
    c = circuit(p, "GateAnd")
    text(c, 70, 50, "M0 / AND truth table")
    source(c,100,100,"A"); source(c,100,150,"B")
    gate(c,"AND",300,120,["A","B"],"Y")
    sink(c,430,120,"Y")
    c = circuit(p, "LoadBit")
    text(c,70,50,"M0 / one bit: Q(next) = Load ? Data : Q; async Reset wins")
    text(c,70,80,"Selection uses NOT / AND / OR gates. Only the single-bit D flip-flop is a foundation.")
    for i,name in enumerate(("Data","Load","Clock","Reset")):
        source(c,100,140+i*60,name)
    invert(c,300,200,"Load","Hold")
    gate(c,"AND",460,160,["Data","Load"],"New")
    gate(c,"AND",460,260,["Q","Hold"],"Old")
    gate(c,"OR",640,220,["New","Old"],"D")
    dff(c,860,210,"D","Clock","Q","Reset","bit")
    sink(c,1100,210,"Q")
    text(c,610,370,"Use the ordinary Clock input pin in sequential vectors.")
    return p


def ram_fixture():
    p = project("RamHarness")
    c = circuit(p,"RamHarness")
    text(c,70,40,"M0 / labelled RAM loading + bounded clocked result")
    text(c,70,70,"Load bank M0_RAM. Address 0 must be A5. halt after two rising edges; pass is a gate-built equality check.")
    component(c,0,"Clock",100,140,highDuration=1,lowDuration=1)
    wire(c,(100,140),(140,140)); tunnel(c,140,140,"Clock")
    constant(c,100,210,0); tunnel(c,100,210,"ZERO")
    constant(c,100,260,1); tunnel(c,100,260,"ONE")
    dff(c,380,130,"ONE","Clock","stage1",name="first_tick")
    dff(c,670,130,"stage1","Clock","halt",name="second_tick")
    sink(c,900,130,"halt")
    # Classic RAM: control height=90 for byte enables with synchronous clock + asynchronous read.
    component(c,4,"RAM",240,340,addrWidth=4,dataWidth=8,appearance="classic",label="M0_RAM",
              labelvisible=True,databus="bibus",enables="byte",asyncread=True,trigger="falling",clearpin=False)
    constant(c,200,350,0,4); wire(c,(200,350),(240,350))
    port(c,240,390,"ZERO")  # WE
    wire(c,(240,400),(160,400),(160,490),(200,490)); tunnel(c,200,490,"ONE")
    port(c,240,410,"Clock")
    constant(c,200,430,0,8); wire(c,(200,430),(240,430))
    port(c,480,430,"signature",8,"right")
    sink(c,650,540,"signature",8)
    # Split byte and compare each bit with the A5 pattern using NOT and AND gates.
    tunnel(c,720,350,"signature",8,"east")
    component(c,0,"Splitter",720,350,incoming=8,fanout=8,appear="right",facing="east",spacing=2)
    for bit in range(8):
        wire(c,(740,360+20*bit),(790,360+20*bit))
        tunnel(c,790,360+20*bit,f"b{bit}")
    for bit in (1,3,4,6):
        invert(c,960,340+bit*50,f"b{bit}",f"n{bit}")
    terms = [f"b{i}" if 0xA5 & (1<<i) else f"n{i}" for i in range(8)]
    for i in range(4):
        gate(c,"AND",1130,360+i*90,terms[2*i:2*i+2],f"p{i}")
    gate(c,"AND",1310,410,["p0","p1"],"lowOK")
    gate(c,"AND",1310,580,["p2","p3"],"highOK")
    gate(c,"AND",1480,500,["lowOK","highOK"],"pass")
    sink(c,1720,500,"pass")
    return p


def mouse_workbench():
    p=project("M0Workbench",bridge=True)
    c=circuit(p,"M0Workbench")
    text(c,60,40,"BITWRIGHT M0 / host I/O feasibility workbench")
    text(c,60,70,"No CPU or circuit FIFO yet. Host adapters are visibly separate. Use the Poke tool; enable ticks for live echo / mouse.")
    component(c,0,"Clock",100,150,highDuration=1,lowDuration=1,label="HostClock")
    wire(c,(100,150),(150,150)); tunnel(c,150,150,"Clock")
    source(c,100,200,"Reset")
    source(c,100,250,"Clear")
    source(c,100,300,"Ack")
    source(c,100,350,"OverflowClear")
    text(c,60,410,"Reset clears host state. Ack held high drains mouse packets one per falling edge.")
    text(c,60,435,"Ack low preserves the front packet while mouse events queue; outputs on the right show it.")
    text(c,300,125,"ASCII Keyboard -> TTY / both sample on rising edges")
    component(c,5,"Keyboard",330,190,buflen=32,trigger="rising")
    port(c,330,190,"Clock")
    wire(c,(340,200),(340,260),(390,260)); tunnel(c,390,260,"Available")
    wire(c,(350,200),(350,230),(400,230)); tunnel(c,400,230,"Reset")
    wire(c,(460,200),(460,280),(510,280)); tunnel(c,510,280,"Available")
    wire(c,(470,200),(510,200)); tunnel(c,510,200,"ASCII",7)
    component(c,5,"TTY",670,240,rows=6,cols=28,trigger="rising")
    wire(c,(670,230),(620,230),(620,210),(600,210)); tunnel(c,600,210,"ASCII",7,"east")
    wire(c,(670,240),(630,240),(630,340),(670,340)); tunnel(c,670,340,"Clock")
    wire(c,(680,250),(680,300),(730,300)); tunnel(c,730,300,"Available")
    wire(c,(690,250),(690,280),(740,280)); tunnel(c,740,280,"Reset")
    text(c,60,470,"Manual pixel inputs for the stock display")
    for i,(label,width) in enumerate((("X",7),("Y",7),("Color",3),("Plot",1))):
        source(c,100,530+i*50,label,width)
    # The stock video samples rising edges: invert Clock to align with bridge falling edges.
    invert(c,300,700,"Clock","PixelClock")
    gate(c,"OR",410,820,["Reset","Clear"],"VideoReset")
    component(c,5,"RGB Video",440,650,width=128,height=128,scale=1,color="8-Color RGB (3 bit)",cursor="No Cursor",reset="Asynchronous")
    for dx,label,width in ((0,"VideoReset",1),(10,"PixelClock",1),(20,"Plot",1),(40,"X",7),(50,"Y",7),(60,"Color",3)):
        wire(c,(440+dx,650),(440+dx,670+dx*2),(560+dx,670+dx*2))
        tunnel(c,560+dx,670+dx*2,label,width)
    text(c,410,505,"Stock RGB Video")
    component(c,10,"BitwrightCanvas",850,510)
    text(c,820,480,"Host bridge: retained pixels + press / drag / release")
    for dy,label,width in ((20,"Clock",1),(40,"Reset",1),(60,"CanvasPlot",1),(80,"Clear",1),(100,"MouseX",7),(120,"MouseY",7),(140,"Color",3),(160,"Ack",1),(180,"OverflowClear",1)):
        port(c,850,510+dy,label,width)
    for dy,label,width in ((20,"MouseValid",1),(40,"MouseX",7),(60,"MouseY",7),(80,"MouseButtons",3),(100,"MouseOverflow",1)):
        port(c,1030,510+dy,label,width,"right")
        sink(c,1450,510+dy,label,width)
    text(c,810,770,"Mouse events only: this is the host queue, not the future machine's 16-event FIFO.")
    text(c,810,795,"To paint: set Color, Plot=1, Ack=1; enable ticks and press / drag on the canvas.")
    text(c,810,820,"Gates echo coordinates to the pixel bus; the bridge only obeys bus commands.")
    tunnel(c,1080,900,"MouseButtons",3,"east")
    component(c,0,"Splitter",1080,900,incoming=3,fanout=3,appear="right",facing="east")
    wire(c,(1100,910),(1150,910)); tunnel(c,1150,910,"PrimaryDown")
    gate(c,"AND",480,910,["MouseValid","PrimaryDown"],"MouseDrawing")
    gate(c,"AND",730,970,["MouseDrawing","Plot"],"CanvasPlot")
    return p


def terminal_control(p):
    """The same inspectable gate circuit is instantiated by the real front panel."""
    c = circuit(p, "TerminalControl")
    # Explicit appearance makes subcircuit ports reproducible and keeps the front panel compact.
    c.find("a[@name='appearance']").set("val", "custom")
    shape = E.SubElement(c, "appear")
    E.SubElement(shape, "rect", x="0", y="0", width="220", height="160", fill="#ffffff", stroke="#000000", **{"stroke-width":"2"})
    for y, label in ((20,"Run"),(60,"Clear"),(100,"Reset"),(140,"Available")):
        E.SubElement(shape,"text", x="10", y=str(y+4), fill="#000000", **{"font-family":"SansSerif","font-size":"12"}).text=label
    for y, label in ((40,"Transfer"),(80,"TtyClear"),(120,"KeyboardClear")):
        E.SubElement(shape,"text", x="210", y=str(y+4), fill="#000000", **{"font-family":"SansSerif","font-size":"12","text-anchor":"end"}).text=label
    E.SubElement(shape,"text",x="110",y="78",fill="#000000", **{"font-family":"SansSerif","font-size":"12","text-anchor":"middle"}).text="Terminal"
    E.SubElement(shape,"text",x="110",y="94",fill="#000000", **{"font-family":"SansSerif","font-size":"12","text-anchor":"middle"}).text="control"
    for y, source_y in ((20,140),(60,200),(100,260),(140,320)):
        E.SubElement(shape,"circ-port",x="0",y=str(y),dir="in",pin=f"100,{source_y}")
    for y, source_y in ((40,140),(80,220),(120,300)):
        E.SubElement(shape,"circ-port",x="220",y=str(y),dir="out",pin=f"980,{source_y}")
    E.SubElement(shape,"circ-anchor",x="220",y="80",facing="east")
    text(c,60,50,"Terminal control / Run and Available permit one transfer; Clear or Reset inhibits it")
    for y,label in ((140,"Run"),(200,"Clear"),(260,"Reset"),(320,"Available")):
        source(c,100,y,label)
    gate(c,"OR",390,240,["Clear","Reset"],"TtyClear")
    invert(c,560,300,"TtyClear","NotClear")
    gate(c,"AND",390,140,["Run","Available"],"Ready")
    gate(c,"AND",730,140,["Ready","NotClear"],"Transfer")
    sink(c,980,140,"Transfer")
    sink(c,980,220,"TtyClear")
    sink(c,980,300,"KeyboardClear",signal="Reset")
    text(c,60,400,"No gated clock: Run and clear controls gate data transfer, while the source clock keeps running.")
    return c


def workbench():
    p = project("M0Workbench")
    E.SubElement(p, "lib", name="11", desc="file#manual/foundations.circ")
    c = circuit(p,"M0Workbench")
    # This is a circuit attribute, not a project option. Simulator.setPropagator reads it.
    attr(c, simulationFrequency="64.0")
    text(c,60,40,"BITWRIGHT / M0 KEYBOARD TERMINAL")
    text(c,60,75,"Use Poke, enable clock ticks, click the Keyboard, and type ASCII. Run=1 forwards characters.")
    text(c,60,105,"Stock host adapters + gate-built control. No CPU or machine FIFO yet. No Java library required.")
    source(c,140,190,"Run",initial=1)
    source(c,140,250,"Clear",initial=0)
    source(c,140,310,"Reset",initial=0)
    text(c,60,365,"Run=0: hold queued input.")
    text(c,60,390,"Clear=1: clear screen, hold queued input.")
    text(c,60,415,"Reset=1: clear screen and input queue.")
    component(c,0,"Clock",140,470,highDuration=1,lowDuration=1,label="HostClock")
    wire(c,(140,470),(180,470)); tunnel(c,180,470,"SysClock")
    text(c,60,520,"64 ticks/s; 32 transfers/s.")
    text(c,60,545,"Clock keeps running.")
    text(c,340,180,"KEYBOARD / click here, then type")
    component(c,5,"Keyboard",340,220,buflen=32,trigger="rising")
    port(c,340,220,"SysClock")
    wire(c,(350,230),(350,320),(390,320)); tunnel(c,390,320,"Transfer")
    wire(c,(360,230),(360,270),(400,270)); tunnel(c,400,270,"KClear")
    wire(c,(470,230),(470,290),(510,290)); tunnel(c,510,290,"Available")
    wire(c,(480,230),(520,230)); tunnel(c,520,230,"ASCII",7)
    text(c,690,170,"TEXT MONITOR / 32 columns x 8 rows")
    component(c,5,"TTY",690,340,rows=8,cols=32,trigger="rising")
    wire(c,(690,330),(630,330),(630,230),(610,230)); tunnel(c,610,230,"ASCII",7,"east")
    wire(c,(690,340),(650,340),(650,450),(690,450)); tunnel(c,690,450,"SysClock")
    wire(c,(700,350),(700,410),(740,410)); tunnel(c,740,410,"Transfer")
    wire(c,(710,350),(710,380),(750,380)); tunnel(c,750,380,"TtyClear")
    E.SubElement(c,"comp",name="TerminalControl",loc=loc(590,550))
    for y,label in ((490,"Run"),(530,"Clear"),(570,"Reset"),(610,"Available")):
        port(c,370,y,label)
    for y,label in ((510,"Transfer"),(550,"TtyClear"),(590,"KeyboardClear")):
        port(c,590,y,"KClear" if label == "KeyboardClear" else label,side="right")
    text(c,370,660,"Inspect TerminalControl to see the gates.")
    for y,label,width,signal in ((210,"Available",1,None),(260,"ASCII",7,None),(310,"Transfer",1,None),(360,"TtyClear",1,None),(410,"KeyboardClear",1,"KClear"),(460,"ClockSeen",1,"SysClock")):
        sink(c,1130,y,label,width,signal)
    text(c,940,530,"Observable circuit pins")
    text(c,940,555,"ASCII stays at the queued front byte.")
    text(c,940,580,"Available=1 means input is waiting.")
    terminal_control(p)
    return p


def never_halt():
    p = project("NeverHalt")
    c = circuit(p, "NeverHalt")
    text(c, 80, 60, "Intentional non-termination fixture: runner must enforce a timeout")
    component(c, 0, "Clock", 100, 120)
    wire(c, (100, 120), (200, 120))
    pin(c, 200, 120, "clock_seen", output=True)
    constant(c, 100, 180, 0)
    wire(c, (100, 180), (200, 180))
    pin(c, 200, 180, "halt", output=True)
    return p


def serialize(p):
    E.indent(p,space="  ")
    # ElementTree's declaration for a Unicode writer varies with Python's UTF-8
    # mode/locale ("UTF-8" versus "utf-8"). Pin it independently of host settings.
    return '<?xml version="1.0" encoding="UTF-8"?>\n'+E.tostring(p,encoding="unicode")+"\n"


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true",help="compare only; never write")
    parser.add_argument("--experiment",action="store_true",help="also generate/check the optional mouse-canvas experiment")
    args=parser.parse_args()
    outputs={"circuits/generated/foundations.circ":foundations(),"circuits/generated/ram-harness.circ":ram_fixture(),"circuits/terminal-bench.circ":workbench(),"circuits/generated/never-halt.circ":never_halt()}
    if args.experiment:
        outputs["experiments/mouse-canvas/workbench.circ"] = mouse_workbench()
    stale=[]
    for relative,p in outputs.items():
        path=ROOT/relative; data=serialize(p)
        if args.check:
            if not path.exists() or path.read_text()!=data: stale.append(relative)
        else:
            path.parent.mkdir(parents=True,exist_ok=True); path.write_text(data)
    if stale:
        parser.exit(1,"Stale generated circuits: "+", ".join(stale)+"\n")
    print("Generated circuit artifacts are current." if args.check else f"Generated {len(outputs)} native circuit projects.")


if __name__=="__main__":
    main()
